# Site settings
title: Shounok Rahman
description: Shounok's Resume
favicon: /assets/img/avatar.JPG
url: https://Shounok.github.io/
rss_url: /pages/atom.xml
google_analytics: UA-63653234-1
show_downloads: true

# Build settings
markdown: kramdown

exclude: [vendor]

# Author settings
author:
  name: Shounok Rahman
  title: Software Engineer
  address: Dhaka, Bangladesh
  email: shounok0207@gmail.com
  link: http://shounok.github.io
  weibo:
  github: Shounok
  linkedin: shounok-rahman-a2193763
  twitter: shounokv
  gavatar: /resumecard/assets/img/avatar.JPG
  stackoverflow:
#  stackoverflow: 4582127
  workHistory:
  - work1:
      company: Tiller
      location: Dhaka, Bangladesh
      title: Software Engineer
      started: 2021
      duration: (July, 2021 - Present)
      description: I switch between back-end and front-end every now and then. Sometimes I manage AI projects here. I get to work with GIS too.
    - work2:
      company: Trenza Softwares
      location: Dhaka, Bangladesh
      title: Web Developer
      started: 2020
      duration: (December, 2020 - June, 2021)
      description: I was coordinating between various projects running for the company. As a project coordinator, my responsibility was to develop products for different clients according to their requirements.
    - work3:
      company: Xoss Technologies Ltd.
      location: Dhaka, Bangladesh
      title: Web Developer
      started: 2018
      duration: (October, 2018 - May, 2020)
      description: I was coordinating between various projects running for the company. As a project coordinator, my responsibility was to develop Software Development plan, managing and scheduling different tasks. As a developer, I was in charge with managing server-side ends of different projects.

  educationHistory:
    - education1:
      organization: Khulna University
      location: Khulna, Bangladesh
      degree: Bachelor's
      major: Computer Science and Engineering
      started: 2010
      duration: (2010 - 2017)
    - education2:
      organization: American International University - Bangladesh
      location: Dhaka, Bangladesh
      degree: Master's
      major: Computer Science
      started: 2020
      duration: (2020 - Ongoing)
  languages:
    - language1:
      name: Bangla
      proficiency: Native
    - language2:
      name: English
      proficiency: Professional
    - language3:
      name: Hindi
      proficiency: Limited
  programmingSkills:
    - skill1:
      name: PHP
      percentage: 85%
    - skill2:
      name: JavaScript
      percentage: 80%
    - skill3:
      name: Python
      percentage: 65%      
    - skill4:
      name: Data Science
      percentage: 30%
    - skill5:
      name: Java/Android
      percentage: 60%
